FROM apache/airflow:slim-2.11.0-python3.11

USER root

RUN apt-get update \
    &&  apt-get install -y --no-install-recommends \
        nano git mc \
        curl \
        unixodbc-dev \
        libgssapi-krb5-2 \
        pkg-config \ 
        build-essential \
        libmysqlclient-dev \
        libxml2-dev \ 
        libxmlsec1-dev \
        libxmlsec1-openssl \
    && curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc \
    && curl https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY ./requirements.txt .

RUN  pip install uv && pip install --no-cache-dir --upgrade pip \
    && uv pip install --no-cache-dir -r requirements.txt \
    && rm -rf /var/lib/apt/lists/*
