FROM apache/airflow:2.9.1-python3.11
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         nano git mc \
  # ----------------mssql block---------------------
  && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -  \
  && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list  \
  && apt-get update  \
  && apt-get -y install unixodbc-dev \
  && apt-get -y install -y libgssapi-krb5-2 \
  && ACCEPT_EULA=Y apt-get -y install msodbcsql18 \
  && ACCEPT_EULA=Y apt-get -y install mssql-tools18 \
  # -------------------------------------------------
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install --user -r requirements.txt