FROM apache/airflow:slim-2.9.1-python3.11

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nano git mc \
        curl \
        unixodbc-dev \
        libgssapi-krb5-2 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | tee /etc/apt/trusted.gpg.d/microsoft.asc \
    && curl https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*  # Clean up temporary files

USER airflow
WORKDIR /opt/airflow

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt