FROM apache/airflow:2.8.4-python3.11
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         nano git mc \
  &&  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -  \
  && curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list  \
  && apt-get update  \
  && ACCEPT_EULA=Y apt-get -y install msodbcsql17 \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install --user -r requirements.txt